bazar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.mainpage, name='home'),
    path('register', views.RegisterUser.as_view(), name='register'),
    path('login', views.LoginUser.as_view(), name='login'),
    path('logout', views.logout_user, name='logout'),
    path('profile', views.profile, name='profile'),
    path('product/<int:id>', views.ProductPage),
    path('product/<int:id>/', views.ProductPage, name="product"),
    path('toggle-favorite/', views.toggle_favorite, name='toggle_favorite'),
    path('cart', views.CartPage, name="cart"),
    path('special', views.special, name="special"),
    path('category/<int:id>/', views.categorys, name="category"),
    path('add-product/', views.add_product, name='add_product'),
    path('load-categories/', views.load_categories, name='load_categories'),
    path('search/', views.search, name='search'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from datetime import date
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.urls import reverse
from bazar import settings


class City(models.Model):
    city = models.CharField(verbose_name='Город', blank=True, max_length=300)

    def __str__(self):
        return str(self.city)

    class Meta:
        verbose_name = "Город"
        verbose_name_plural = "Города"


class User(AbstractUser):
    username = models.CharField(default="123", max_length=255)
    email = models.EmailField(
        verbose_name='Электронная почта',
        max_length=255,
        unique=True,
    )
    phonenumber = models.CharField(verbose_name="Номер телефона", blank=True, max_length=13, validators=[RegexValidator(r'^(\+375|80)(29|25|44|33)(\d{3})(\d{2})(\d{2})$')])
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, verbose_name="Город")
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class Maincategory(models.Model):
    maincategoryName = models.CharField(verbose_name='Название основной категории', max_length=50, unique=True)

    def __str__(self):
        return str(self.maincategoryName)

    class Meta:
        verbose_name = "Основная категория"
        verbose_name_plural = "Основные категории"


class Category(models.Model):
    maincategoryName = models.ForeignKey(Maincategory, on_delete=models.CASCADE, null=False, verbose_name="Главная категория")
    categoryName = models.CharField(verbose_name='Подкатегория', max_length=50, unique=True)

    def __str__(self):
        return str(self.categoryName)

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"


class Product(models.Model):
    QUALITY_CHOICES = (
        ('new', 'Новое'),
        ('used', 'Б/У'),
    )
    name = models.CharField(verbose_name='Название', unique=False, max_length=50)
    cost = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, verbose_name="Подкатегория")
    description = models.TextField(verbose_name='Описание', blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, verbose_name="Город")
    views = models.BigIntegerField(verbose_name="Количество просмотров", default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Пользователь")
    dateAdd = models.DateTimeField('Дата добавления', default=timezone.now)
    visible_phone = models.BooleanField('Видимость номера')
    quality = models.CharField(max_length=4, choices=QUALITY_CHOICES)
    is_exchange = models.BooleanField('Возможен обмен')
    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('product', kwargs={"id": self.id})

    def update_views(self, *args, **kwargs):
        self.views = self.views + 1
        super(Product, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering=['name']


class Photo(models.Model):
    photo = models.ImageField(verbose_name='Фото', upload_to="img/", blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True,verbose_name="Товар")

    def __str__(self):
        return str(self.product) + "(" + str(self.photo)+")"

    class Meta:
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Пользователь")
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Товар")
    dateAdd = models.DateField('Дата добавления', default=date.today)

    def __str__(self):
        return str(self.user)+" "+str(self.Product)

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзина"
        unique_together = ('user', 'Product')

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from multiupload.fields import MultiFileField
from .models import *
from django.forms import ModelForm, inlineformset_factory, ClearableFileInput


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-input-reg', 'placeholder': 'Email' }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input-reg', 'placeholder': 'Пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input-reg', 'placeholder':'Повтор пароля'}))

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input-reg', 'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input-reg', 'placeholder': 'Пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField(label='Электронная почта:', widget=forms.EmailInput())
    first_name = forms.CharField(label='Имя:', widget=forms.TextInput())
    last_name = forms.CharField(label='Фамилия:', widget=forms.TextInput())
    phonenumber = forms.CharField(label='Номер телефона:')
    city = forms.CharField(label='Город:', widget=forms.TextInput())

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'city', 'phonenumber']


class ProductForm(forms.ModelForm):
    photos = MultiFileField(min_num=1, max_num=10, max_file_size=1024*1024*5, required=False)  # Максимум 10 фотографий размером до 5 МБ

    class Meta:
        model = Product
        fields = ['name', 'cost', 'category', 'description', 'city']

    def clean_photos(self):
        photos = self.cleaned_data.get('photos')
        if photos and len(photos) > 10:
            raise forms.ValidationError('Максимальное количество фотографий - 10')
        return photos

main/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.db.models import Q
from django.db.models.functions import Lower
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.views.generic import CreateView
from main.forms import *
from main.models import *
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm
from .models import Product

def mainpage(request):
    Products = Product.objects.all().order_by('-dateAdd')[:30]
    photos = Photo.objects.all()
    context = {
        'title': 'bazar.by - торговая площадка объявлений',
        'Products': Products,
        'photos': photos
    }
    return render(request, 'main/index.html', context)


def base(request):
    AllMainCategory = Maincategory.objects.all()
    AllCategory = Category.objects.all()
    context = {
        'AllMainCategory': AllMainCategory,
        'AllCategory': AllCategory,
    }
    return render(request, 'base.html', context)


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = "main/register.html"
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'main/login.html'

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')


def profile(request):
    products = Product.objects.filter(user_id=request.user.id)
    AllUserInfo = User.objects.filter(id=request.user.id)

    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            return redirect(to='profile')
    else:
        user_form = UpdateUserForm(instance=request.user)

    context = {
        'Products': products,
        'title': 'Профиль',
        'AllUserInfo': AllUserInfo,
        'user_form': user_form
    }
    return render(request, 'main/profile.html', context)


def ProductPage(request, id):
    product = get_object_or_404(Product, pk=id)
    photos = Photo.objects.filter(product_id=id)
    carts = Cart.objects.all()
    if request.user.is_authenticated:
        carts = Cart.objects.filter(Product=id, user=request.user)
    print(carts)
    post = Product.objects.get(id=id)
    post.update_views()

    context = {
        'title': product,
        'product': product,
        'photos': photos,
        'carts': carts
    }
    return render(request, 'main/productcard.html', context)



def categorys(request, id):
    category = get_object_or_404(Category, pk=id)
    allProducts = Product.objects.filter(category=category.id)
    return render(request, 'main/category.html', {"title":category, 'allProducts':allProducts})

def special(request):
    SpecialProducts = Product.objects.exclude(costwithdiscount=None).order_by('-views')
    return render(request, 'main/special.html', {"title":"Специальные предложения", 'SpecialProducts':SpecialProducts})


@login_required
@ensure_csrf_cookie
def toggle_favorite(request):
    product_id = request.POST.get('product_id')
    user = request.user

    try:
        cart_item = Cart.objects.get(user=user, Product_id=product_id)
        cart_item.delete()
        message = 'removed'
    except Cart.DoesNotExist:
        cart_item = Cart(user=user, Product_id=product_id)
        cart_item.save()
        message = 'added'

    response = {'message': message}
    return JsonResponse(response)




def CartPage(request):
    carts = Cart.objects.all()
    countincart = 0
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user)
        countincart = carts.count()
    return render(request,'main/cart.html', {'title':'Корзина', 'carts':carts, 'countincart': countincart})


@login_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            form.save_m2m()  # Сохранение связанных данных, например, категорий
            return redirect('home')  # Перенаправление на главную страницу после успешного добавления
    else:
        form = ProductForm()
    return render(request, 'main/add_product.html', {'form': form})


def load_categories(request):
    maincategory_id = request.GET.get('maincategoryName_id')
    categories = Category.objects.filter(maincategoryName_id=maincategory_id)
    category_options = [(category.id, category.categoryName) for category in categories]
    return JsonResponse({'categories': category_options})

def search(request):
    query = request.GET.get('q')
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    quality = request.GET.get('quality')
    is_exchange = request.GET.get('is_exchange')
    products = Product.objects.all()
    has_photo = request.GET.get('has_photo')
    sort = request.GET.get('sort')
    print('query:', query)
    if is_exchange:
        products = products.filter(is_exchange=True)

    if quality:
        products = products.filter(quality=quality)

    if query:
        products = products.filter(Q(name__icontains=query.lower()))
    if min_price:
        products = products.filter(cost__gte=min_price)

    if max_price:
        products = products.filter(cost__lte=max_price)

    if has_photo:
        product_ids_with_photo = Photo.objects.values_list('product_id', flat=True).distinct()
        products = products.filter(id__in=product_ids_with_photo)

    if sort == 'newest':
        products = products.order_by('-dateAdd')
    elif sort == 'cheapest':
        products = products.order_by('cost')
    elif sort == 'expensive':
        products = products.order_by('-cost')
    if query is "":
        products = ""
        query = ""
    context = {
        'products': products,
        'query': query,
    }
    return render(request, 'main/search.html', context)

main/templates/main/add_product.html
{% extends 'main/base.html' %}

{% block content %}
  <h2>Добавить продукт</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <label for="id_maincategoryName">Основная категория:</label>
      <select id="id_maincategoryName" name="maincategoryName">
        <option value="">---------</option>
        {% for maincategory in maincategories %}
          <option value="{{ maincategory.id }}">{{ maincategory.maincategoryName }}</option>
        {% endfor %}
      </select>
    </div>
    <div id="subcategory-select">
      <label for="id_category">Подкатегория:</label>
      <select id="id_category" name="category" disabled>
        <option value="">---------</option>
      </select>
    </div>
    <div>
      <label for="id_name">Название:</label>
      <input type="text" id="id_name" name="name" required>
    </div>
    <div>
      <label for="id_cost">Цена:</label>
      <input type="number" id="id_cost" name="cost" step="0.01" required>
    </div>
    <div>
      <label for="id_description">Описание:</label>
      <textarea id="id_description" name="description"></textarea>
    </div>
    <div>
      <label for="id_city">Город:</label>
      <input type="text" id="id_city" name="city">
    </div>
    <div>
      <label for="id_photos">Фотографии:</label>
      <input type="file" id="id_photos" name="photos" accept="image/*" multiple required>
      <div id="photo-preview"></div>
    </div>
    <button type="submit">Добавить</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#id_maincategoryName').change(function () {
        var maincategoryId = $(this).val();
        if (maincategoryId) {
          $.ajax({
            url: '/load-categories/',
            data: {
              'maincategoryName_id': maincategoryId
            },
            dataType: 'json',
            success: function (data) {
              var categories = data.categories;
              var categorySelect = $('#id_category');
              categorySelect.empty();
              if (categories.length > 0) {
                categorySelect.removeAttr('disabled');
                for (var i = 0; i < categories.length; i++) {
                  var category = categories[i];
                  categorySelect.append($('<option>').val(category[0]).text(category[1]));
                }
              } else {
                categorySelect.attr('disabled', true);
              }
            }
          });
        } else {
          $('#id_category').empty().attr('disabled', true);
        }
      });

      $('#id_photos').change(function () {
        var files = Array.from(this.files);
        var previewContainer = $('#photo-preview');
        previewContainer.empty();
        if (files.length > 10) {
          alert('Максимальное количество фотографий - 10');
          this.value = '';  // Сбросить выбранные файлы
          return;
        }
        files.forEach(function (file) {
          var reader = new FileReader();
          reader.onload = function (e) {
            var img = $('<img>').attr('src', e.target.result).addClass('photo-thumbnail');
            var removeBtn = $('<button>').text('X').addClass('remove-photo');
            var photoContainer = $('<div>').addClass('photo-container').append(img, removeBtn);
            previewContainer.append(photoContainer);
          };
          reader.readAsDataURL(file);
        });
      });

      $('#photo-preview').on('click', '.remove-photo', function () {
        $(this).parent('.photo-container').remove();
      });
    });
  </script>
  <style>
    .photo-thumbnail {
      width: 100px;
      height: 100px;
      object-fit: cover;
    }

    .photo-container {
      display: inline-block;
      margin-right: 10px;
    }

    .remove-photo {
      color: red;
      font-weight: bold;
      cursor: pointer;
    }
  </style>
{% endblock %}

main/templates/main/cart.html
{% extends 'main/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    {% if carts %}
           <div class="styles_listings__content__77Bve">

              <div class="styles_content__right__ddauo">
                <div class="styles_wrapper__PRxpS">
                  <div class="styles_breadcrumbs__wrapper__a3Iz7"></div>
                  <h1 class="styles_title__t0hUI">Избранное</h1>
                  <div class="styles_wrapper__EXbXU">
                    <div class="styles_inner__5_Bu9">В избранном: {{ countincart }}</div>
                  </div>

                </div>
                <div data-name="listings">
                  <div class="styles_wrapper__Td0CN">
                    <div class="styles_cards___qpff">

                     {% for cart in carts %}
    {% with photo=cart.Product.photo_set.first %}
        <section>
            <a class="styles_wrapper__yaLfq" href="product/{{ cart.Product.id }}">
                <div class="styles_image__QXHZP">
                    <div class="styles_container__Gcb8J">
                        <div class="styles_image__UV4Wa">
                            <div class="styles_container__9vxyc" style="padding-top:100%">
                                <div class="styles_image__KiLWw">
                                    <div class="styles_container__dR7XZ">
                                        <img src="{{ photo.photo.url }}" class="styles_image__eGgZr lazyload" alt="{{ cart.Product.name }}" loading="lazy">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="styles_border__4CZRX"></div>
                    </div>
                </div>
                <div class="styles_content__BDDGV">
                    <div class="styles_top__HNf3a">
                        <div>
                            <p class="styles_price__9JZaB"><span>{{ cart.Product.cost }}</span><span></span></p>
                        </div>
                    </div>
                    <h3 class="styles_title__ARIVF">{{ cart.Product.name }}</h3>
                    <div class="styles_secondary__NEYhw">
                        <p>{{ cart.Product.city }}</p><span>{{ cart.Product.dateAdd }}</span>
                    </div>
                </div>
            </a>
        </section>
    {% endwith %}
{% endfor %}


                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

    {% else %}
        <h3 class="text-center mt-3">Корзина пустая! <a href="{% url 'home' %}">Главная</a></h3>
    {% endif %}
      {% else %}
    <h3 class="text-center mt-3">Вы не вошли в аккаунт! <a href="{% url 'login' %}">Войти?</a></h3>
    {% endif %}

{% endblock %}

main/templates/main/category.html
{% extends 'main/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

{% if allProducts %}
    <div class="container mt-3 mb-3">
    <a class="link h5" href="">{{ category.categoryName }}</a>
    <div class="row">
        {% for Products in allProducts %}
        {% if Products.costwithdiscount is not None %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="product-card">
                {% load static %}
                <a href="product/{{ Products.id }}"><img src="{{ Products.photo.url }}" alt=""></a>
                <span class="product-name">{{ Products.name }}</span>
                <div class="product-costs">
                    <span class="product-cost">{{ Products.costwithdiscount }} BYN</span>
                    <span class="product-cost-discount">{{ Products.Cost }} BYN</span>
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="product-card">
                <a href="product/{{ Products.id }}"><img src="{{ Products.photo.url }}" alt=""></a>
                <span class="product-name">{{ Products.name }}</span>
                <span class="product-cost">{{ Products.Cost }} BYN</span>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}

{% endblock %}

main/templates/main/chat.html
{% extends 'main/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="styles_container__wYL0x styles_container-children__VyrUd">
          <div>
            <div class="style_main_page_wrapper__JZnAW">
              <div class="style_left_part__KUvH_">
                <div>
                  <div class="styles_label__nQvxm">Популярные категории</div>
                  <div class="styles_wrapper__pc_KW styles_slider_container__WH1kX styles_right_rectangle__AS8iM">
                    <div class="swiper">
                      <div class="swiper-wrapper">

                        <div class="swiper-slide styles_slide__iInrb"><a class="styles_element__CgYpE" id="16000" href="l/kompyuternaya-tehnika57e4.html?elementType=popular_categories"><span>Компьютерная техника</span></a><a class="styles_element__CgYpE" id="15000" href="l/bytovaya-tehnika57e4.html?elementType=popular_categories"><span>Бытовая техника</span></a><a class="styles_element__CgYpE" id="19000" href="l/muzhskoj-garderob57e4.html?elementType=popular_categories"><span>Мужской гардероб</span></a></div>


                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
            <div class="styles_listings__content__77Bve">

              <div class="styles_content__right__ddauo">
                <div class="styles_wrapper__PRxpS">
                  <div class="styles_breadcrumbs__wrapper__a3Iz7"></div>
                  <h1 class="styles_title__t0hUI">Недавние объявления</h1>
                  <div class="styles_wrapper__EXbXU">
                    <div class="styles_inner__5_Bu9">
                        cdcddcscdscdscs
                    </div>
                  </div>

                </div>
                <div data-name="listings">
                  <div class="styles_wrapper__Td0CN">
                    <div class="styles_cards___qpff">

                     {% for Product in Products %}
    {% with photo=Product.photo_set.first %}
        <section>
            <a class="styles_wrapper__yaLfq" href="product/{{ Product.id }}">
                <div class="styles_image__QXHZP">
                    <div class="styles_container__Gcb8J">
                        <div class="styles_image__UV4Wa">
                            <div class="styles_container__9vxyc" style="padding-top:100%">
                                <div class="styles_image__KiLWw">
                                    <div class="styles_container__dR7XZ">
                                        <img src="{{ photo.photo.url }}" class="styles_image__eGgZr lazyload" alt="{{ Product.name }}" loading="lazy">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="styles_border__4CZRX"></div>
                    </div>
                </div>
                <div class="styles_content__BDDGV">
                    <div class="styles_top__HNf3a">
                        <div>
                            <p class="styles_price__9JZaB"><span>{{ Product.cost }}</span><span></span></p>
                        </div>
                    </div>
                    <h3 class="styles_title__ARIVF">{{ Product.name }}</h3>
                    <div class="styles_secondary__NEYhw">
                        <p>{{ Product.city }}</p><span>{{ Product.dateAdd }}</span>
                    </div>
                </div>
            </a>
        </section>
    {% endwith %}
{% endfor %}


                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

{% endblock %}

main/templates/main/productcard.html
  {% extends 'main/base.html' %}
  {% block title %}{{ title }}{% endblock %}
  {% block content %}
<div style="display: flex">
<swiper-container class="mySwiper" pagination="true" pagination-clickable="true" navigation="true" space-between="30" loop="true">
    {% for photo in photos %}
    <swiper-slide><img src="{{ photo.photo.url }}"></swiper-slide>

    {% endfor %}

</swiper-container>


<div class="right_product">
     <h1 class="styles_brief_wrapper__title__x59rm" data-name="av_title">{{ product.name }}</h1>
    <div>
        <span class="styles_brief_wrapper__date__FfOke">{{ product.dateAdd }},</span>
      <span class="styles_address__fQyGA">{{ product.city }}</span>
        <div>
            <span class="styles_address__fQyGA">{{ product.get_quality_display  }},</span>
            <span class="styles_address__fQyGA">{% if product.is_exchange %}Возможен обмен{% else %}Обмен не предлагать{% endif %}</span>
        </div>
    </div>
 <div class="styles_container__OjHTs styles_brief_wrapper__price__V9gxE">
     <span class="styles_main__9wZlb">{{ product.cost }} р.</span>
 </div>


{% if user.is_authenticated %}
    <button class="product-button favorite-button" data-product-id="{{ product.id }}">Добавить в избранное</button>
{% else %}
    <a class="product-button" href="/login">Войти, чтобы добавить в избранное</a>
{% endif %}




</div>
</div>





    <div class="seller-block">
      <h2 class="seller_header_2">Продавец</h2>

       <div class="seller_flex">
         <div class="seller_image_block">
            <img src="/media/img/svg/user_avatar.svg">
         </div>
         <div class="seller_right">
           <div class="styles_seller-block__top-right__lC2Lm">
             <div class="seller_username">
                 <a href="">{{ product.user.first_name }}</a>
              </div>
             <p>{{ product.user.first_name }}</p>
             <div class="seller_contacts">
                 {% if product.visible_phone %}
                   <button class="modal-button product-button">Позвонить</button>
                 {% endif %}
              <a>Написать</a>
             </div>
           </div>
         </div>
       </div>
    </div>



<div class="styles_description__XFqmz">
  <div data-name="description-block" class="styles_description__vsEQQ" style="max-height:144px">
    <h2 class="styles_description__title__H_4cK">Описание</h2>
    <div itemprop="description">{{ product.description }}<br></div>
  </div>
</div>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const favoriteButtons = document.querySelectorAll('.favorite-button');
        favoriteButtons.forEach(button => {
            button.addEventListener('click', function() {
                const productId = button.getAttribute('data-product-id');
                toggleFavorite(productId, button);
            });
        });
    });

    function toggleFavorite(productId, button) {
        const csrftoken = getCookie('csrftoken');

        fetch('/toggle-favorite/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'X-CSRFToken': csrftoken
            },
            body: `product_id=${productId}`
        })
        .then(response => response.json())
        .then(data => {
            if (data.message === 'added') {
                button.textContent = 'Удалить из избранного';
                button.classList.add('favorited');
            } else if (data.message === 'removed') {
                button.textContent = 'Добавить в избранное';
                button.classList.remove('favorited');
            }
        })
        .catch(error => {
            console.error('Произошла ошибка:', error);
        });
    }

    // Функция для получения значения CSRF-токена из куки
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) {
            return parts.pop().split(';').shift();
        }
    }
</script>

{% if product.visible_phone %}


<div class="modal-overlay">
    <div class="modal-content">
        <h2>Номер телефона продавца {{ product.user.first_name }}:</h2>
        <p>{{ product.user.phonenumber }}</p>
        <button class="modal-close product-button">Окей</button>
    </div>
</div>

<style>
    .modal-overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 9999;
    }

    .modal-content {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 330px;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
    }
     .modal-content p{
        text-align: center;
         margin: 5px;
    }

    .modal-close {
        margin-top: 10px;
        text-align: center;
    }
</style>

<script>
    const modalButton = document.querySelector('.modal-button');
    const modalOverlay = document.querySelector('.modal-overlay');
    const modalClose = document.querySelector('.modal-close');

    modalButton.addEventListener('click', function() {
        modalOverlay.style.display = 'block';
    });

    modalClose.addEventListener('click', function() {
        modalOverlay.style.display = 'none';
    });
</script>

{% endif %}



{% endblock %}